#!/bin/bash
set -euo pipefail
if jsonschema --help 2>&1 | grep -q pretty; then
  out=( -o pretty )
else
  out=()
fi
yamllint "$@"
for recipe in "$@"; do
  echo "$recipe"
  PYTHONWARNINGS=ignore jsonschema "${out[@]}" \
    -i <( "${PYTHON:-python3}" scripts/yaml2json < "$recipe" ) \
    schemas/recipe.json
done
