#!/bin/bash
set -euo pipefail
if jsonschema --help 2>&1 | grep -q pretty; then
  out=( -o pretty )
else
  out=()
fi
for log in "$@"; do
  echo "$log"
  if [ "$log" = index.json ]; then
    PYTHONWARNINGS=ignore jsonschema "${out[@]}" -i index.json schemas/log-index.json
  else
    PYTHONWARNINGS=ignore jsonschema "${out[@]}" -i "$log" schemas/log.json
  fi
done
