#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 FC (Fay) Stegerman <flx@obfusk.net>
# SPDX-License-Identifier: AGPL-3.0-or-later
import json
import sys
from ruamel.yaml import YAML
json.dump(YAML(typ="safe").load(sys.stdin), sys.stdout, indent=2)
print()
