name: update recipes
on:
  workflow_dispatch:
  schedule:
    - cron: '3 0 * * *'
permissions:
  actions: none
  checks: none
  contents: write
  deployments: none
  discussions: none
  id-token: none
  issues: none
  packages: none
  pages: none
  pull-requests: write
  repository-projects: none
  security-events: none
  statuses: none
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
          submodules: true
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt
      - name: Update recipes
        run: python3 scripts/update-recipes.py -v --continue-on-errors --update-hashes recipes/*.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create pull request
        uses: peter-evans/create-pull-request@v7.0.5
        with:
          title: "Update recipes"
          commit-message: "Update recipes"
          branch-suffix: timestamp
